

### list_models
POST http://127.0.0.1:8888/v1/embeddings
Content-Type: application/json

{
    "model": "vicuna-13b-v1.5-16k",
    "input": "user",
    "temperature": 1,
    "top_p": 1,
    "n": 1,
    "max_tokens": 1024
}

### 
POST http://127.0.0.1:21002/worker_get_embeddings
Content-Type: application/json

{
    "model": "vicuna-13b-v1.5-16k",
    "input": [
        "怎样计算圆形面积"
    ]
}

####
POST http://127.0.0.1:21001/get_worker_address
Content-Type: application/json

{
    "model": "vicuna-13b-v1.5-16k"
}


####
POST http://127.0.0.1:21002/worker_generate_completion
Content-Type: application/json

{
    "max_new_tokens": 256,
    "model": "vicuna-13b-v1.5-16k",
    "prompt": "USER: 你好 ASSISTANT: ",
    "stream": false,
    "temperature": 1,
    "top_p": 1
}

####
POST http://192.168.6.2:8888/chat/completions
Content-Type: application/json

{
    "max_new_tokens": 50,
    "model": "vicuna-13b-v1.5-16k",
    "prompt": "USER: 你好 ASSISTANT: ",
    "stream": true,
    "temperature": 1,
    "top_p": 1
}