import 'package:omnigram/service/tts/models/tts_voice.dart';

// https://help.aliyun.com/zh/isi/developer-reference/overview-of-speech-synthesis#5186fe1abb7ag
const List<TtsVoice> aliyunVoices = [
  TtsVoice(
    shortName: 'abin',
    name: '阿斌',
    locale: 'zh-CN',
    gender: 'male',
    description: '广东普通话',
  ),
  TtsVoice(
    shortName: 'zhixiaobai',
    name: '知小白',
    locale: 'zh-CN',
    gender: 'female',
    description: '普通话女声',
  ),
  TtsVoice(
    shortName: 'zhixiaoxia',
    name: '知小夏',
    locale: 'zh-CN',
    gender: 'female',
    description: '普通话女声',
  ),
  TtsVoice(
    shortName: 'zhixiaomei',
    name: '知小妹',
    locale: 'zh-CN',
    gender: 'female',
    description: '普通话女声',
  ),
  TtsVoice(
    shortName: 'zhigui',
    name: '知柜',
    locale: 'zh-CN',
    gender: 'female',
    description: '普通话女声',
  ),
  TtsVoice(
    shortName: 'zhishuo',
    name: '知硕',
    locale: 'zh-CN',
    gender: 'male',
    description: '普通话男声',
  ),
  TtsVoice(
    shortName: 'aixia',
    name: '艾夏',
    locale: 'zh-CN',
    gender: 'female',
    description: '普通话女声',
  ),
  TtsVoice(
    shortName: 'cally',
    name: 'Cally',
    locale: 'en-US',
    gender: 'female',
    description: 'American English (female)',
  ),
  TtsVoice(
    shortName: 'zhifeng_emo',
    name: '知锋_多情感',
    locale: 'zh-CN',
    gender: 'male',
    description: '多种情感男声',
  ),
  TtsVoice(
    shortName: 'zhibing_emo',
    name: '知冰_多情感',
    locale: 'zh-CN',
    gender: 'male',
    description: '多种情感男声',
  ),
  TtsVoice(
    shortName: 'zhimiao_emo',
    name: '知妙_多情感',
    locale: 'zh-CN',
    gender: 'female',
    description: '多种情感女声',
  ),
  TtsVoice(
    shortName: 'zhimi_emo',
    name: '知米_多情感',
    locale: 'zh-CN',
    gender: 'female',
    description: '多种情感女声',
  ),
  TtsVoice(
    shortName: 'zhiyan_emo',
    name: '知燕_多情感',
    locale: 'zh-CN',
    gender: 'female',
    description: '多种情感女声',
  ),
  TtsVoice(
    shortName: 'zhibei_emo',
    name: '知贝_多情感',
    locale: 'zh-CN',
    gender: 'female',
    description: '多种情感童声',
  ),
  TtsVoice(
    shortName: 'zhitian_emo',
    name: '知甜_多情感',
    locale: 'zh-CN',
    gender: 'female',
    description: '多种情感女声',
  ),
  TtsVoice(
    shortName: 'xiaoyun',
    name: '小云',
    locale: 'zh-CN',
    gender: 'female',
    description: '标准女声',
  ),
  TtsVoice(
    shortName: 'xiaogang',
    name: '小刚',
    locale: 'zh-CN',
    gender: 'male',
    description: '标准男声',
  ),
  TtsVoice(
    shortName: 'ruoxi',
    name: '若兮',
    locale: 'zh-CN',
    gender: 'female',
    description: '温柔女声',
  ),
  TtsVoice(
    shortName: 'siqi',
    name: '思琪',
    locale: 'zh-CN',
    gender: 'female',
    description: '温柔女声',
  ),
  TtsVoice(
    shortName: 'sijia',
    name: '思佳',
    locale: 'zh-CN',
    gender: 'female',
    description: '标准女声',
  ),
  TtsVoice(
    shortName: 'sicheng',
    name: '思诚',
    locale: 'zh-CN',
    gender: 'male',
    description: '标准男声',
  ),
  TtsVoice(
    shortName: 'aiqi',
    name: '艾琪',
    locale: 'zh-CN',
    gender: 'female',
    description: '温柔女声',
  ),
  TtsVoice(
    shortName: 'aijia',
    name: '艾佳',
    locale: 'zh-CN',
    gender: 'female',
    description: '标准女声',
  ),
  TtsVoice(
    shortName: 'aicheng',
    name: '艾诚',
    locale: 'zh-CN',
    gender: 'male',
    description: '标准男声',
  ),
  TtsVoice(
    shortName: 'aida',
    name: '艾达',
    locale: 'zh-CN',
    gender: 'male',
    description: '标准男声',
  ),
  TtsVoice(
    shortName: 'ninger',
    name: '宁儿',
    locale: 'zh-CN',
    gender: 'female',
    description: '标准女声',
  ),
  TtsVoice(
    shortName: 'ruilin',
    name: '瑞琳',
    locale: 'zh-CN',
    gender: 'female',
    description: '标准女声',
  ),
  TtsVoice(
    shortName: 'siyue',
    name: '思悦',
    locale: 'zh-CN',
    gender: 'female',
    description: '温柔女声',
  ),
  TtsVoice(
    shortName: 'aiya',
    name: '艾雅',
    locale: 'zh-CN',
    gender: 'female',
    description: '严厉女声',
  ),
  TtsVoice(
    shortName: 'aimei',
    name: '艾美',
    locale: 'zh-CN',
    gender: 'female',
    description: '甜美女声',
  ),
  TtsVoice(
    shortName: 'aiyu',
    name: '艾雨',
    locale: 'zh-CN',
    gender: 'female',
    description: '自然女声',
  ),
  TtsVoice(
    shortName: 'aiyue',
    name: '艾悦',
    locale: 'zh-CN',
    gender: 'female',
    description: '温柔女声',
  ),
  TtsVoice(
    shortName: 'aijing',
    name: '艾婧',
    locale: 'zh-CN',
    gender: 'female',
    description: '严厉女声',
  ),
  TtsVoice(
    shortName: 'xiaomei',
    name: '小美',
    locale: 'zh-CN',
    gender: 'female',
    description: '甜美女声',
  ),
  TtsVoice(
    shortName: 'aina',
    name: '艾娜',
    locale: 'zh-CN',
    gender: 'female',
    description: '浙普女声',
  ),
  TtsVoice(
    shortName: 'yina',
    name: '伊娜',
    locale: 'zh-CN',
    gender: 'female',
    description: '浙普女声',
  ),
  TtsVoice(
    shortName: 'sijing',
    name: '思婧',
    locale: 'zh-CN',
    gender: 'female',
    description: '严厉女声',
  ),
  TtsVoice(
    shortName: 'sitong',
    name: '思彤',
    locale: 'zh-CN',
    gender: 'female',
    description: '儿童音',
  ),
  TtsVoice(
    shortName: 'xiaobei',
    name: '小北',
    locale: 'zh-CN',
    gender: 'female',
    description: '萝莉女声',
  ),
  TtsVoice(
    shortName: 'aitong',
    name: '艾彤',
    locale: 'zh-CN',
    gender: 'female',
    description: '儿童音',
  ),
  TtsVoice(
    shortName: 'aiwei',
    name: '艾薇',
    locale: 'zh-CN',
    gender: 'female',
    description: '萝莉女声',
  ),
  TtsVoice(
    shortName: 'aibao',
    name: '艾宝',
    locale: 'zh-CN',
    gender: 'female',
    description: '萝莉女声',
  ),
  TtsVoice(
    shortName: 'harry',
    name: 'Harry',
    locale: 'en-GB',
    gender: 'male',
    description: 'British English (male)',
  ),
  TtsVoice(
    shortName: 'abby',
    name: 'Abby',
    locale: 'en-US',
    gender: 'female',
    description: 'American English (female)',
  ),
  TtsVoice(
    shortName: 'andy',
    name: 'Andy',
    locale: 'en-US',
    gender: 'male',
    description: 'American English (male)',
  ),
  TtsVoice(
    shortName: 'eric',
    name: 'Eric',
    locale: 'en-GB',
    gender: 'male',
    description: 'British English (male)',
  ),
  TtsVoice(
    shortName: 'emily',
    name: 'Emily',
    locale: 'en-GB',
    gender: 'female',
    description: 'British English (female)',
  ),
  TtsVoice(
    shortName: 'luna',
    name: 'Luna',
    locale: 'en-GB',
    gender: 'female',
    description: 'British English (female)',
  ),
  TtsVoice(
    shortName: 'luca',
    name: 'Luca',
    locale: 'en-GB',
    gender: 'male',
    description: 'British English (male)',
  ),
  TtsVoice(
    shortName: 'wendy',
    name: 'Wendy',
    locale: 'en-GB',
    gender: 'female',
    description: 'British English (female)',
  ),
  TtsVoice(
    shortName: 'william',
    name: 'William',
    locale: 'en-GB',
    gender: 'male',
    description: 'British English (male)',
  ),
  TtsVoice(
    shortName: 'olivia',
    name: 'Olivia',
    locale: 'en-GB',
    gender: 'female',
    description: 'British English (female)',
  ),
  TtsVoice(
    shortName: 'shanshan',
    name: '姗姗',
    locale: 'yu e',
    gender: 'female',
    description: '粤语女声',
  ),
  TtsVoice(
    shortName: 'aiyuan',
    name: '艾媛',
    locale: 'zh-CN',
    gender: 'female',
    description: '知心姐姐',
  ),
  TtsVoice(
    shortName: 'aiying',
    name: '艾颖',
    locale: 'zh-CN',
    gender: 'female',
    description: '软萌童声',
  ),
  TtsVoice(
    shortName: 'aixiang',
    name: '艾祥',
    locale: 'zh-CN',
    gender: 'male',
    description: '磁性男声',
  ),
  TtsVoice(
    shortName: 'aimo',
    name: '艾墨',
    locale: 'zh-CN',
    gender: 'male',
    description: '情感男声',
  ),
  TtsVoice(
    shortName: 'aiye',
    name: '艾晔',
    locale: 'zh-CN',
    gender: 'male',
    description: '青年男声',
  ),
  TtsVoice(
    shortName: 'aiting',
    name: '艾婷',
    locale: 'zh-CN',
    gender: 'female',
    description: '电台女声',
  ),
  TtsVoice(
    shortName: 'aifan',
    name: '艾凡',
    locale: 'zh-CN',
    gender: 'female',
    description: '情感女声',
  ),
  TtsVoice(
    shortName: 'lydia',
    name: 'Lydia',
    locale: 'en-US',
    gender: 'female',
    description: 'English-Chinese bilingual (female)',
  ),
  TtsVoice(
    shortName: 'chuangirl',
    name: '小玥',
    locale: 'zh-CN',
    gender: 'female',
    description: '四川话女声',
  ),
  TtsVoice(
    shortName: 'aishuo',
    name: '艾硕',
    locale: 'zh-CN',
    gender: 'male',
    description: '自然男声',
  ),
  TtsVoice(
    shortName: 'qingqing',
    name: '青青',
    locale: 'zh-TW',
    gender: 'female',
    description: '中国台湾话女声',
  ),
  TtsVoice(
    shortName: 'cuijie',
    name: '翠姐',
    locale: 'zh-CN',
    gender: 'female',
    description: '东北话女声',
  ),
  TtsVoice(
    shortName: 'xiaoze',
    name: '小泽',
    locale: 'zh-CN',
    gender: 'male',
    description: '湖南重口音男声',
  ),
  TtsVoice(
    shortName: 'ainan',
    name: '艾楠',
    locale: 'zh-CN',
    gender: 'male',
    description: '广告男声',
  ),
  TtsVoice(
    shortName: 'aihao',
    name: '艾浩',
    locale: 'zh-CN',
    gender: 'male',
    description: '资讯男声',
  ),
  TtsVoice(
    shortName: 'aiming',
    name: '艾茗',
    locale: 'zh-CN',
    gender: 'male',
    description: '诙谐男声',
  ),
  TtsVoice(
    shortName: 'aixiao',
    name: '艾笑',
    locale: 'zh-CN',
    gender: 'female',
    description: '资讯女声',
  ),
  TtsVoice(
    shortName: 'aichu',
    name: '艾厨',
    locale: 'zh-CN',
    gender: 'male',
    description: '舌尖男声',
  ),
  TtsVoice(
    shortName: 'aiqian',
    name: '艾倩',
    locale: 'zh-CN',
    gender: 'female',
    description: '资讯女声',
  ),
  TtsVoice(
    shortName: 'tomoka',
    name: '智香',
    locale: 'ja-JP',
    gender: 'female',
    description: '日语女声',
  ),
  TtsVoice(
    shortName: 'tomoya',
    name: '智也',
    locale: 'ja-JP',
    gender: 'male',
    description: '日语男声',
  ),
  TtsVoice(
    shortName: 'annie',
    name: 'Annie',
    locale: 'en-US',
    gender: 'female',
    description: 'American English (female)',
  ),
  TtsVoice(
    shortName: 'aishu',
    name: '艾树',
    locale: 'zh-CN',
    gender: 'male',
    description: '资讯男声',
  ),
  TtsVoice(
    shortName: 'airu',
    name: '艾茹',
    locale: 'zh-CN',
    gender: 'female',
    description: '新闻女声',
  ),
  TtsVoice(
    shortName: 'jiajia',
    name: '佳佳',
    locale: 'yue',
    gender: 'female',
    description: '粤语女声',
  ),
  TtsVoice(
    shortName: 'indah',
    name: 'Indah',
    locale: 'id-ID',
    gender: 'female',
    description: 'Indonesian (female)',
  ),
  TtsVoice(
    shortName: 'taozi',
    name: '桃子',
    locale: 'yue',
    gender: 'female',
    description: '粤语女声',
  ),
  TtsVoice(
    shortName: 'guijie',
    name: '柜姐',
    locale: 'zh-CN',
    gender: 'female',
    description: '亲切女声',
  ),
  TtsVoice(
    shortName: 'stella',
    name: 'Stella',
    locale: 'en-US',
    gender: 'female',
    description: 'Warm female',
  ),
  TtsVoice(
    shortName: 'stanley',
    name: 'Stanley',
    locale: 'en-US',
    gender: 'male',
    description: 'Calm male',
  ),
  TtsVoice(
    shortName: 'kenny',
    name: 'Kenny',
    locale: 'en-US',
    gender: 'male',
    description: 'Calm male',
  ),
  TtsVoice(
    shortName: 'rosa',
    name: 'Rosa',
    locale: 'en-US',
    gender: 'female',
    description: 'Natural female',
  ),
  TtsVoice(
    shortName: 'farah',
    name: 'Farah',
    locale: 'ms-MY',
    gender: 'female',
    description: 'Malay (female)',
  ),
  TtsVoice(
    shortName: 'mashu',
    name: '马树',
    locale: 'zh-CN',
    gender: 'male',
    description: '儿童剧男声',
  ),
  TtsVoice(
    shortName: 'zhiqi',
    name: '知琪',
    locale: 'zh-CN',
    gender: 'female',
    description: '温柔女声',
  ),
  TtsVoice(
    shortName: 'zhichu',
    name: '知厨',
    locale: 'zh-CN',
    gender: 'male',
    description: '舌尖男声',
  ),
  TtsVoice(
    shortName: 'xiaoxian',
    name: '小仙',
    locale: 'zh-CN',
    gender: 'female',
    description: '亲切女声',
  ),
  TtsVoice(
    shortName: 'yuer',
    name: '悦儿',
    locale: 'zh-CN',
    gender: 'female',
    description: '儿童剧女声',
  ),
  TtsVoice(
    shortName: 'maoxiaomei',
    name: '猫小美',
    locale: 'zh-CN',
    gender: 'female',
    description: '活力女声',
  ),
  TtsVoice(
    shortName: 'zhixiang',
    name: '知祥',
    locale: 'zh-CN',
    gender: 'male',
    description: '磁性男声',
  ),
  TtsVoice(
    shortName: 'zhijia',
    name: '知佳',
    locale: 'zh-CN',
    gender: 'female',
    description: '标准女声',
  ),
  TtsVoice(
    shortName: 'zhinan',
    name: '知楠',
    locale: 'zh-CN',
    gender: 'male',
    description: '广告男声',
  ),
  TtsVoice(
    shortName: 'zhiqian',
    name: '知倩',
    locale: 'zh-CN',
    gender: 'female',
    description: '资讯女声',
  ),
  TtsVoice(
    shortName: 'zhiru',
    name: '知茹',
    locale: 'zh-CN',
    gender: 'female',
    description: '新闻女声',
  ),
  TtsVoice(
    shortName: 'zhide',
    name: '知德',
    locale: 'zh-CN',
    gender: 'male',
    description: '新闻男声',
  ),
  TtsVoice(
    shortName: 'zhifei',
    name: '知飞',
    locale: 'zh-CN',
    gender: 'male',
    description: '激昂解说',
  ),
  TtsVoice(
    shortName: 'aifei',
    name: '艾飞',
    locale: 'zh-CN',
    gender: 'male',
    description: '激昂解说',
  ),
  TtsVoice(
    shortName: 'yaqun',
    name: '亚群',
    locale: 'zh-CN',
    gender: '',
    description: '卖场广播',
  ),
  TtsVoice(
    shortName: 'qiaowei',
    name: '巧薇',
    locale: 'zh-CN',
    gender: '',
    description: '卖场广播',
  ),
  TtsVoice(
    shortName: 'dahu',
    name: '大虎',
    locale: 'zh-CN',
    gender: 'male',
    description: '东北话男声',
  ),
  TtsVoice(
    shortName: 'ava',
    name: 'ava',
    locale: 'en-US',
    gender: 'female',
    description: 'American English (female)',
  ),
  TtsVoice(
    shortName: 'zhilun',
    name: '知伦',
    locale: 'zh-CN',
    gender: 'male',
    description: '悬疑解说',
  ),
  TtsVoice(
    shortName: 'ailun',
    name: '艾伦',
    locale: 'zh-CN',
    gender: 'male',
    description: '悬疑解说',
  ),
  TtsVoice(
    shortName: 'jielidou',
    name: '杰力豆',
    locale: 'zh-CN',
    gender: '',
    description: '治愈童声',
  ),
  TtsVoice(
    shortName: 'zhiwei',
    name: '知薇',
    locale: 'zh-CN',
    gender: 'female',
    description: '萝莉女声',
  ),
  TtsVoice(
    shortName: 'laotie',
    name: '老铁',
    locale: 'zh-CN',
    gender: 'male',
    description: '东北老铁',
  ),
  TtsVoice(
    shortName: 'laomei',
    name: '老妹',
    locale: 'zh-CN',
    gender: 'female',
    description: '吆喝女声',
  ),
  TtsVoice(
    shortName: 'aikan',
    name: '艾侃',
    locale: 'zh-CN',
    gender: 'male',
    description: '天津话男声',
  ),
  TtsVoice(
    shortName: 'tala',
    name: 'Tala',
    locale: 'fil-PH',
    gender: 'female',
    description: 'Filipino (female)',
  ),
  TtsVoice(
    shortName: 'zhitian',
    name: '知甜',
    locale: 'zh-CN',
    gender: 'female',
    description: '甜美女声',
  ),
  TtsVoice(
    shortName: 'zhiqing',
    name: '知青',
    locale: 'zh-TW',
    gender: 'female',
    description: '中国台湾话女生',
  ),
  TtsVoice(
    shortName: 'tien',
    name: 'Tien',
    locale: 'vi-VN',
    gender: 'female',
    description: 'Vietnamese (female)',
  ),
  TtsVoice(
    shortName: 'becca',
    name: 'Becca',
    locale: 'en-US',
    gender: 'female',
    description: 'American English (female)',
  ),
  TtsVoice(
    shortName: 'Kyong',
    name: 'Kyong',
    locale: 'ko-KR',
    gender: 'female',
    description: 'Korean (female)',
  ),
  TtsVoice(
    shortName: 'masha',
    name: 'masha',
    locale: 'ru-RU',
    gender: 'female',
    description: 'Russian (female)',
  ),
  TtsVoice(
    shortName: 'camila',
    name: 'camila',
    locale: 'es-ES',
    gender: 'female',
    description: 'Spanish (female)',
  ),
  TtsVoice(
    shortName: 'perla',
    name: 'perla',
    locale: 'it-IT',
    gender: 'female',
    description: 'Italian (female)',
  ),
  TtsVoice(
    shortName: 'zhimao',
    name: '知猫',
    locale: 'zh-CN',
    gender: 'female',
    description: '普通话女声',
  ),
  TtsVoice(
    shortName: 'zhiyuan',
    name: '知媛',
    locale: 'zh-CN',
    gender: 'female',
    description: '普通话女声',
  ),
  TtsVoice(
    shortName: 'zhiya',
    name: '知雅',
    locale: 'zh-CN',
    gender: 'female',
    description: '普通话女声',
  ),
  TtsVoice(
    shortName: 'zhiyue',
    name: '知悦',
    locale: 'zh-CN',
    gender: 'female',
    description: '普通话女声',
  ),
  TtsVoice(
    shortName: 'zhida',
    name: '知达',
    locale: 'zh-CN',
    gender: 'male',
    description: '普通话男声',
  ),
  TtsVoice(
    shortName: 'zhistella',
    name: '知莎',
    locale: 'zh-CN',
    gender: 'female',
    description: '普通话女声',
  ),
  TtsVoice(
    shortName: 'kelly',
    name: 'Kelly',
    locale: 'yue',
    gender: 'female',
    description: '香港粤语女声',
  ),
  TtsVoice(
    shortName: 'clara',
    name: 'clara',
    locale: 'fr-FR',
    gender: 'female',
    description: 'French (female)',
  ),
  TtsVoice(
    shortName: 'hanna',
    name: 'hanna',
    locale: 'de-DE',
    gender: 'female',
    description: 'German (female)',
  ),
  TtsVoice(
    shortName: 'waan',
    name: 'waan',
    locale: 'th-TH',
    gender: 'female',
    description: 'Thai (female)',
  ),
  TtsVoice(
    shortName: 'betty',
    name: 'betty',
    locale: 'en-US',
    gender: 'female',
    description: 'American English (female)',
  ),
  TtsVoice(
    shortName: 'beth',
    name: 'beth',
    locale: 'en-US',
    gender: 'female',
    description: 'American English (female)',
  ),
  TtsVoice(
    shortName: 'cindy',
    name: 'cindy',
    locale: 'en-US',
    gender: 'female',
    description: 'American English (female)',
  ),
  TtsVoice(
    shortName: 'donna',
    name: 'donna',
    locale: 'en-US',
    gender: 'female',
    description: 'American English (female)',
  ),
  TtsVoice(
    shortName: 'eva',
    name: 'eva',
    locale: 'en-US',
    gender: 'female',
    description: 'American English (female)',
  ),
  TtsVoice(
    shortName: 'brian',
    name: 'brian',
    locale: 'en-US',
    gender: 'male',
    description: 'American English (male)',
  ),
  TtsVoice(
    shortName: 'david',
    name: 'david',
    locale: 'en-US',
    gender: 'male',
    description: 'American English (male)',
  ),
  TtsVoice(
    shortName: 'abby_ecmix',
    name: 'abby_ecmix',
    locale: 'en-US',
    gender: 'female',
    description: 'American English (female)',
  ),
  TtsVoice(
    shortName: 'annie_ecmix',
    name: 'annie_ecmix',
    locale: 'en-US',
    gender: 'female',
    description: 'American English (female)',
  ),
  TtsVoice(
    shortName: 'andy_ecmix',
    name: 'andy_ecmix',
    locale: 'en-US',
    gender: 'male',
    description: 'American English (male)',
  ),
  TtsVoice(
    shortName: 'ava_ecmix',
    name: 'ava_ecmix',
    locale: 'en-US',
    gender: 'female',
    description: 'American English (female)',
  ),
  TtsVoice(
    shortName: 'betty_ecmix',
    name: 'betty_ecmix',
    locale: 'en-US',
    gender: 'female',
    description: 'American English (female)',
  ),
  TtsVoice(
    shortName: 'beth_ecmix',
    name: 'beth_ecmix',
    locale: 'en-US',
    gender: 'female',
    description: 'American English (female)',
  ),
  TtsVoice(
    shortName: 'brian_ecmix',
    name: 'brian_ecmix',
    locale: 'en-US',
    gender: 'male',
    description: 'American English (male)',
  ),
  TtsVoice(
    shortName: 'cindy_ecmix',
    name: 'cindy_ecmix',
    locale: 'en-US',
    gender: 'female',
    description: 'American English (female)',
  ),
  TtsVoice(
    shortName: 'cally_ecmix',
    name: 'cally_ecmix',
    locale: 'en-US',
    gender: 'female',
    description: 'American English (female)',
  ),
  TtsVoice(
    shortName: 'donna_ecmix',
    name: 'donna_ecmix',
    locale: 'en-US',
    gender: 'female',
    description: 'American English (female)',
  ),
  TtsVoice(
    shortName: 'david_ecmix',
    name: 'david_ecmix',
    locale: 'en-US',
    gender: 'male',
    description: 'American English (male)',
  ),
  TtsVoice(
    shortName: 'eva_ecmix',
    name: 'eva_ecmix',
    locale: 'en-US',
    gender: 'female',
    description: 'American English (female)',
  ),
];
