# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: m4t.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tm4t.proto\x12\x03m4t\"K\n\x0bTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0c\n\x04lang\x18\x02 \x01(\t\x12\x10\n\x08\x61udio_id\x18\x03 \x01(\t\x12\x0e\n\x06\x66ormat\x18\x04 \x01(\x05\"C\n\x0eUploadRequsest\x12\x1d\n\x07speaker\x18\x01 \x01(\x0b\x32\x0c.m4t.Speaker\x12\x12\n\naudio_data\x18\x02 \x01(\x0c\"\x1e\n\x0b\x44\x65lRequsest\x12\x0f\n\x07\x61udioID\x18\x01 \x01(\t\"\x0f\n\rEmptyRequsest\"\x8e\x01\n\x07Speaker\x12\x10\n\x08\x61udio_id\x18\x01 \x01(\t\x12\x0e\n\x06gender\x18\x02 \x01(\x05\x12\x14\n\x0c\x64\x65\x66\x61ult_type\x18\x03 \x01(\x08\x12\x14\n\x0c\x64isplay_name\x18\x05 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x06 \x01(\t\x12\x12\n\navatar_url\x18\x07 \x01(\t\x12\x0c\n\x04path\x18\x08 \x01(\t\"-\n\x0bSpeakerList\x12\x1e\n\x08speakers\x18\x01 \x03(\x0b\x32\x0c.m4t.Speaker\"#\n\rAudioResponse\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x32\x91\x02\n\x0bTextToAudio\x12:\n\x12\x43onvertTextToAudio\x12\x10.m4t.TextRequest\x1a\x12.m4t.AudioResponse\x12\x33\n\tTTSStream\x12\x10.m4t.TextRequest\x1a\x12.m4t.AudioResponse0\x01\x12\x32\n\nAllSpeaker\x12\x12.m4t.EmptyRequsest\x1a\x10.m4t.SpeakerList\x12/\n\nAddSpeaker\x12\x13.m4t.UploadRequsest\x1a\x0c.m4t.Speaker\x12,\n\nDelSpeaker\x12\x10.m4t.DelRequsest\x1a\x0c.m4t.SpeakerB$Z\"github.com/omnigram-server/api/m4tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'm4t_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\"github.com/omnigram-server/api/m4t'
  _globals['_TEXTREQUEST']._serialized_start=18
  _globals['_TEXTREQUEST']._serialized_end=93
  _globals['_UPLOADREQUSEST']._serialized_start=95
  _globals['_UPLOADREQUSEST']._serialized_end=162
  _globals['_DELREQUSEST']._serialized_start=164
  _globals['_DELREQUSEST']._serialized_end=194
  _globals['_EMPTYREQUSEST']._serialized_start=196
  _globals['_EMPTYREQUSEST']._serialized_end=211
  _globals['_SPEAKER']._serialized_start=214
  _globals['_SPEAKER']._serialized_end=356
  _globals['_SPEAKERLIST']._serialized_start=358
  _globals['_SPEAKERLIST']._serialized_end=403
  _globals['_AUDIORESPONSE']._serialized_start=405
  _globals['_AUDIORESPONSE']._serialized_end=440
  _globals['_TEXTTOAUDIO']._serialized_start=443
  _globals['_TEXTTOAUDIO']._serialized_end=716
# @@protoc_insertion_point(module_scope)
