// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.12.4
// source: m4t.proto

package m4t

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TextRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text    string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Lang    string `protobuf:"bytes,2,opt,name=lang,proto3" json:"lang,omitempty"`
	AudioId string `protobuf:"bytes,3,opt,name=audio_id,json=audioId,proto3" json:"audio_id,omitempty"`
	Format  int32  `protobuf:"varint,4,opt,name=format,proto3" json:"format,omitempty"`
}

func (x *TextRequest) Reset() {
	*x = TextRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_m4t_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextRequest) ProtoMessage() {}

func (x *TextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_m4t_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextRequest.ProtoReflect.Descriptor instead.
func (*TextRequest) Descriptor() ([]byte, []int) {
	return file_m4t_proto_rawDescGZIP(), []int{0}
}

func (x *TextRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TextRequest) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *TextRequest) GetAudioId() string {
	if x != nil {
		return x.AudioId
	}
	return ""
}

func (x *TextRequest) GetFormat() int32 {
	if x != nil {
		return x.Format
	}
	return 0
}

type UploadRequsest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Speaker   *Speaker `protobuf:"bytes,1,opt,name=speaker,proto3" json:"speaker,omitempty"`
	AudioData []byte   `protobuf:"bytes,2,opt,name=audio_data,json=audioData,proto3" json:"audio_data,omitempty"`
}

func (x *UploadRequsest) Reset() {
	*x = UploadRequsest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_m4t_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadRequsest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRequsest) ProtoMessage() {}

func (x *UploadRequsest) ProtoReflect() protoreflect.Message {
	mi := &file_m4t_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadRequsest.ProtoReflect.Descriptor instead.
func (*UploadRequsest) Descriptor() ([]byte, []int) {
	return file_m4t_proto_rawDescGZIP(), []int{1}
}

func (x *UploadRequsest) GetSpeaker() *Speaker {
	if x != nil {
		return x.Speaker
	}
	return nil
}

func (x *UploadRequsest) GetAudioData() []byte {
	if x != nil {
		return x.AudioData
	}
	return nil
}

type DelRequsest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AudioID string `protobuf:"bytes,1,opt,name=audioID,proto3" json:"audioID,omitempty"`
}

func (x *DelRequsest) Reset() {
	*x = DelRequsest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_m4t_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelRequsest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelRequsest) ProtoMessage() {}

func (x *DelRequsest) ProtoReflect() protoreflect.Message {
	mi := &file_m4t_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelRequsest.ProtoReflect.Descriptor instead.
func (*DelRequsest) Descriptor() ([]byte, []int) {
	return file_m4t_proto_rawDescGZIP(), []int{2}
}

func (x *DelRequsest) GetAudioID() string {
	if x != nil {
		return x.AudioID
	}
	return ""
}

type EmptyRequsest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyRequsest) Reset() {
	*x = EmptyRequsest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_m4t_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyRequsest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequsest) ProtoMessage() {}

func (x *EmptyRequsest) ProtoReflect() protoreflect.Message {
	mi := &file_m4t_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequsest.ProtoReflect.Descriptor instead.
func (*EmptyRequsest) Descriptor() ([]byte, []int) {
	return file_m4t_proto_rawDescGZIP(), []int{3}
}

type Speaker struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AudioId     string `protobuf:"bytes,1,opt,name=audio_id,json=audioId,proto3" json:"audio_id,omitempty"`
	Gender      int32  `protobuf:"varint,2,opt,name=gender,proto3" json:"gender,omitempty"`
	DefaultType bool   `protobuf:"varint,3,opt,name=default_type,json=defaultType,proto3" json:"default_type,omitempty"`
	DisplayName string `protobuf:"bytes,5,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description string `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	AvatarUrl   string `protobuf:"bytes,7,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Path        string `protobuf:"bytes,8,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *Speaker) Reset() {
	*x = Speaker{}
	if protoimpl.UnsafeEnabled {
		mi := &file_m4t_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Speaker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Speaker) ProtoMessage() {}

func (x *Speaker) ProtoReflect() protoreflect.Message {
	mi := &file_m4t_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Speaker.ProtoReflect.Descriptor instead.
func (*Speaker) Descriptor() ([]byte, []int) {
	return file_m4t_proto_rawDescGZIP(), []int{4}
}

func (x *Speaker) GetAudioId() string {
	if x != nil {
		return x.AudioId
	}
	return ""
}

func (x *Speaker) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *Speaker) GetDefaultType() bool {
	if x != nil {
		return x.DefaultType
	}
	return false
}

func (x *Speaker) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Speaker) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Speaker) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *Speaker) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type SpeakerList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Speakers []*Speaker `protobuf:"bytes,1,rep,name=speakers,proto3" json:"speakers,omitempty"`
}

func (x *SpeakerList) Reset() {
	*x = SpeakerList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_m4t_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpeakerList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpeakerList) ProtoMessage() {}

func (x *SpeakerList) ProtoReflect() protoreflect.Message {
	mi := &file_m4t_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpeakerList.ProtoReflect.Descriptor instead.
func (*SpeakerList) Descriptor() ([]byte, []int) {
	return file_m4t_proto_rawDescGZIP(), []int{5}
}

func (x *SpeakerList) GetSpeakers() []*Speaker {
	if x != nil {
		return x.Speakers
	}
	return nil
}

type AudioResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AudioData []byte `protobuf:"bytes,1,opt,name=audio_data,json=audioData,proto3" json:"audio_data,omitempty"`
}

func (x *AudioResponse) Reset() {
	*x = AudioResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_m4t_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AudioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioResponse) ProtoMessage() {}

func (x *AudioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_m4t_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioResponse.ProtoReflect.Descriptor instead.
func (*AudioResponse) Descriptor() ([]byte, []int) {
	return file_m4t_proto_rawDescGZIP(), []int{6}
}

func (x *AudioResponse) GetAudioData() []byte {
	if x != nil {
		return x.AudioData
	}
	return nil
}

var File_m4t_proto protoreflect.FileDescriptor

var file_m4t_proto_rawDesc = []byte{
	0x0a, 0x09, 0x6d, 0x34, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6d, 0x34, 0x74,
	0x22, 0x68, 0x0a, 0x0b, 0x54, 0x65, 0x78, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74,
	0x65, 0x78, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x61, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6c, 0x61, 0x6e, 0x67, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x75, 0x64, 0x69, 0x6f,
	0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x75, 0x64, 0x69, 0x6f,
	0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x22, 0x57, 0x0a, 0x0e, 0x55, 0x70,
	0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x73, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x07,
	0x73, 0x70, 0x65, 0x61, 0x6b, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x6d, 0x34, 0x74, 0x2e, 0x53, 0x70, 0x65, 0x61, 0x6b, 0x65, 0x72, 0x52, 0x07, 0x73, 0x70, 0x65,
	0x61, 0x6b, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x5f, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x44,
	0x61, 0x74, 0x61, 0x22, 0x27, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x73, 0x65,
	0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x49, 0x44, 0x22, 0x0f, 0x0a, 0x0d,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x73, 0x65, 0x73, 0x74, 0x22, 0xd7, 0x01,
	0x0a, 0x07, 0x53, 0x70, 0x65, 0x61, 0x6b, 0x65, 0x72, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x75, 0x64,
	0x69, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x75, 0x64,
	0x69, 0x6f, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x21, 0x0a, 0x0c,
	0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0b, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x21, 0x0a, 0x0c, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x5f, 0x75,
	0x72, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72,
	0x55, 0x72, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x37, 0x0a, 0x0b, 0x53, 0x70, 0x65, 0x61, 0x6b,
	0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x08, 0x73, 0x70, 0x65, 0x61, 0x6b, 0x65,
	0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6d, 0x34, 0x74, 0x2e, 0x53,
	0x70, 0x65, 0x61, 0x6b, 0x65, 0x72, 0x52, 0x08, 0x73, 0x70, 0x65, 0x61, 0x6b, 0x65, 0x72, 0x73,
	0x22, 0x2e, 0x0a, 0x0d, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x44, 0x61, 0x74, 0x61,
	0x32, 0x91, 0x02, 0x0a, 0x0b, 0x54, 0x65, 0x78, 0x74, 0x54, 0x6f, 0x41, 0x75, 0x64, 0x69, 0x6f,
	0x12, 0x3a, 0x0a, 0x12, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x54, 0x65, 0x78, 0x74, 0x54,
	0x6f, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x12, 0x10, 0x2e, 0x6d, 0x34, 0x74, 0x2e, 0x54, 0x65, 0x78,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x6d, 0x34, 0x74, 0x2e, 0x41,
	0x75, 0x64, 0x69, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x09,
	0x54, 0x54, 0x53, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x10, 0x2e, 0x6d, 0x34, 0x74, 0x2e,
	0x54, 0x65, 0x78, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x6d, 0x34,
	0x74, 0x2e, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30,
	0x01, 0x12, 0x32, 0x0a, 0x0a, 0x41, 0x6c, 0x6c, 0x53, 0x70, 0x65, 0x61, 0x6b, 0x65, 0x72, 0x12,
	0x12, 0x2e, 0x6d, 0x34, 0x74, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x73,
	0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x6d, 0x34, 0x74, 0x2e, 0x53, 0x70, 0x65, 0x61, 0x6b, 0x65,
	0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2f, 0x0a, 0x0a, 0x41, 0x64, 0x64, 0x53, 0x70, 0x65, 0x61,
	0x6b, 0x65, 0x72, 0x12, 0x13, 0x2e, 0x6d, 0x34, 0x74, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x73, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x6d, 0x34, 0x74, 0x2e, 0x53,
	0x70, 0x65, 0x61, 0x6b, 0x65, 0x72, 0x12, 0x2c, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x53, 0x70, 0x65,
	0x61, 0x6b, 0x65, 0x72, 0x12, 0x10, 0x2e, 0x6d, 0x34, 0x74, 0x2e, 0x44, 0x65, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x73, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x6d, 0x34, 0x74, 0x2e, 0x53, 0x70, 0x65,
	0x61, 0x6b, 0x65, 0x72, 0x42, 0x24, 0x5a, 0x22, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6f, 0x6d, 0x6e, 0x69, 0x67, 0x72, 0x61, 0x6d, 0x2d, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x34, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_m4t_proto_rawDescOnce sync.Once
	file_m4t_proto_rawDescData = file_m4t_proto_rawDesc
)

func file_m4t_proto_rawDescGZIP() []byte {
	file_m4t_proto_rawDescOnce.Do(func() {
		file_m4t_proto_rawDescData = protoimpl.X.CompressGZIP(file_m4t_proto_rawDescData)
	})
	return file_m4t_proto_rawDescData
}

var file_m4t_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_m4t_proto_goTypes = []interface{}{
	(*TextRequest)(nil),    // 0: m4t.TextRequest
	(*UploadRequsest)(nil), // 1: m4t.UploadRequsest
	(*DelRequsest)(nil),    // 2: m4t.DelRequsest
	(*EmptyRequsest)(nil),  // 3: m4t.EmptyRequsest
	(*Speaker)(nil),        // 4: m4t.Speaker
	(*SpeakerList)(nil),    // 5: m4t.SpeakerList
	(*AudioResponse)(nil),  // 6: m4t.AudioResponse
}
var file_m4t_proto_depIdxs = []int32{
	4, // 0: m4t.UploadRequsest.speaker:type_name -> m4t.Speaker
	4, // 1: m4t.SpeakerList.speakers:type_name -> m4t.Speaker
	0, // 2: m4t.TextToAudio.ConvertTextToAudio:input_type -> m4t.TextRequest
	0, // 3: m4t.TextToAudio.TTSStream:input_type -> m4t.TextRequest
	3, // 4: m4t.TextToAudio.AllSpeaker:input_type -> m4t.EmptyRequsest
	1, // 5: m4t.TextToAudio.AddSpeaker:input_type -> m4t.UploadRequsest
	2, // 6: m4t.TextToAudio.DelSpeaker:input_type -> m4t.DelRequsest
	6, // 7: m4t.TextToAudio.ConvertTextToAudio:output_type -> m4t.AudioResponse
	6, // 8: m4t.TextToAudio.TTSStream:output_type -> m4t.AudioResponse
	5, // 9: m4t.TextToAudio.AllSpeaker:output_type -> m4t.SpeakerList
	4, // 10: m4t.TextToAudio.AddSpeaker:output_type -> m4t.Speaker
	4, // 11: m4t.TextToAudio.DelSpeaker:output_type -> m4t.Speaker
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_m4t_proto_init() }
func file_m4t_proto_init() {
	if File_m4t_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_m4t_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TextRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_m4t_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadRequsest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_m4t_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelRequsest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_m4t_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyRequsest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_m4t_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Speaker); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_m4t_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpeakerList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_m4t_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AudioResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_m4t_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_m4t_proto_goTypes,
		DependencyIndexes: file_m4t_proto_depIdxs,
		MessageInfos:      file_m4t_proto_msgTypes,
	}.Build()
	File_m4t_proto = out.File
	file_m4t_proto_rawDesc = nil
	file_m4t_proto_goTypes = nil
	file_m4t_proto_depIdxs = nil
}
