name: Build macOS

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      flutter_version:
        required: true
        type: string
      xcode_version:
        required: true
        type: string

jobs:
  build-macos:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: ${{ inputs.flutter_version }}

      - name: Get Dependencies
        run: |
          flutter --version
          flutter pub get

      - name: Prepare for macOS
        shell: bash
        run: flutter config --enable-macos-desktop

      - name: Build for macOS
        shell: bash
        run: |
          sudo xcode-select -switch /Applications/Xcode_${{ inputs.xcode_version }}.app/Contents/Developer
          flutter gen-l10n
          dart run build_runner build --delete-conflicting-outputs
          chmod +x ./scripts/macos_nosign.sh
          ./scripts/macos_nosign.sh
          flutter build macos
          cd build/macos/Build/Products/Release
          mkdir -p "Omnigram"
          cp -r "Omnigram.app" "Omnigram/Omnigram.app" 2>/dev/null || cp -r "*.app" "Omnigram/"
          ln -s /Applications "Omnigram/Applications"
          hdiutil create -volname "Omnigram" -srcfolder "Omnigram" -ov -format UDZO Omnigram-${{ inputs.version }}.dmg
          ditto -c -k --keepParent "Omnigram.app" "Omnigram-${{ inputs.version }}.zip" 2>/dev/null || ditto -c -k --keepParent *.app "Omnigram-${{ inputs.version }}.zip"

      - name: Rename builds
        run: |
          cd build
          mkdir -p macos
          mv macos/Build/Products/Release/Omnigram-${{ inputs.version }}.dmg macos/Omnigram-macos-${{ inputs.version }}.dmg
          mv macos/Build/Products/Release/Omnigram-${{ inputs.version }}.zip macos/Omnigram-macos-${{ inputs.version }}.zip
        shell: bash

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-artifacts
          path: |
            app/build/macos/*.dmg
            app/build/macos/*.zip
          if-no-files-found: error
